### ISSUE TITLE
Error: request entity too large

### ISSUE THREAD

**Issue by njam** [cargomedia/loggly-github#10]
```
Aug 04 22:13:27 puppet1 node[30825]: Error: request entity too large
Aug 04 22:13:27 puppet1 node[30825]: at readStream (/usr/lib/node_modules/loggly-github/node_modules/raw-body/index.js:196:17)
Aug 04 22:13:27 puppet1 node[30825]: at getRawBody (/usr/lib/node_modules/loggly-github/node_modules/raw-body/index.js:106:12)
Aug 04 22:13:27 puppet1 node[30825]: at read (/usr/lib/node_modules/loggly-github/node_modules/body-parser/lib/read.js:76:3)
Aug 04 22:13:27 puppet1 node[30825]: at textParser (/usr/lib/node_modules/loggly-github/node_modules/body-parser/lib/types/text.js:80:5)
Aug 04 22:13:27 puppet1 node[30825]: at Layer.handle [as handle_request] (/usr/lib/node_modules/loggly-github/node_modules/express/lib/router/layer.js:95:5)
Aug 04 22:13:27 puppet1 node[30825]: at trim_prefix (/usr/lib/node_modules/loggly-github/node_modules/express/lib/router/index.js:312:13)
Aug 04 22:13:27 puppet1 node[30825]: at /usr/lib/node_modules/loggly-github/node_modules/express/lib/router/index.js:280:7
Aug 04 22:13:27 puppet1 node[30825]: at Function.process_params (/usr/lib/node_modules/loggly-github/node_modules/express/lib/router/index.js:330:12)
Aug 04 22:13:27 puppet1 node[30825]: at next (/usr/lib/node_modules/loggly-github/node_modules/express/lib/router/index.js:271:10)
Aug 04 22:13:27 puppet1 node[30825]: at expressInit (/usr/lib/node_modules/loggly-github/node_modules/express/lib/middleware/init.js:33:5)
Aug 04 22:13:27 puppet1 node[30825]: at Layer.handle [as handle_request] (/usr/lib/node_modules/loggly-github/node_modules/express/lib/router/layer.js:95:5)
Aug 04 22:13:27 puppet1 node[30825]: at trim_prefix (/usr/lib/node_modules/loggly-github/node_modules/express/lib/router/index.js:312:13)
Aug 04 22:13:27 puppet1 node[30825]: at /usr/lib/node_modules/loggly-github/node_modules/express/lib/router/index.js:280:7
Aug 04 22:13:27 puppet1 node[30825]: at Function.process_params (/usr/lib/node_modules/loggly-github/node_modules/express/lib/router/index.js:330:12)
Aug 04 22:13:27 puppet1 node[30825]: at next (/usr/lib/node_modules/loggly-github/node_modules/express/lib/router/index.js:271:10)
Aug 04 22:13:27 puppet1 node[30825]: at query (/usr/lib/node_modules/loggly-github/node_modules/express/lib/middleware/query.js:49:5)
```

**Comment by njam** [comment]
Closed by https://github.com/cargomedia/loggly-github/pull/11
